// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvDQ3ECU06X1aU_H0dYdTP43IlvZSKI8',
    appId: '1:546001277191:web:76f93ed1522732b4bd75a2',
    messagingSenderId: '546001277191',
    projectId: 'fitpad-ff2f5',
    authDomain: 'fitpad-ff2f5.firebaseapp.com',
    databaseURL: 'https://fitpad-ff2f5-default-rtdb.firebaseio.com',
    storageBucket: 'fitpad-ff2f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQakYeVuLrNUAxPMLrdZjXuJKGcY2q4k',
    appId: '1:546001277191:android:7b3a657ea2580334bd75a2',
    messagingSenderId: '546001277191',
    projectId: 'fitpad-ff2f5',
    databaseURL: 'https://fitpad-ff2f5-default-rtdb.firebaseio.com',
    storageBucket: 'fitpad-ff2f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQlPPTyQU52SAifE7i5LwcdJ5otAvmGAY',
    appId: '1:546001277191:ios:032ec8e98fc14bf7bd75a2',
    messagingSenderId: '546001277191',
    projectId: 'fitpad-ff2f5',
    databaseURL: 'https://fitpad-ff2f5-default-rtdb.firebaseio.com',
    storageBucket: 'fitpad-ff2f5.appspot.com',
    iosClientId: '546001277191-tieai27oge9lio812s0m284293va3ae8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQlPPTyQU52SAifE7i5LwcdJ5otAvmGAY',
    appId: '1:546001277191:ios:032ec8e98fc14bf7bd75a2',
    messagingSenderId: '546001277191',
    projectId: 'fitpad-ff2f5',
    databaseURL: 'https://fitpad-ff2f5-default-rtdb.firebaseio.com',
    storageBucket: 'fitpad-ff2f5.appspot.com',
    iosClientId: '546001277191-tieai27oge9lio812s0m284293va3ae8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitpad',
  );
}
