export const data = [
  {
    id: 1,
    question_e:"Importance of Electoral Litreacy ?",
    question_h:"चुनावी साक्षरता का महत्व ?",
    question_k:"ಚುನಾವಣಾ ಸಾಕ್ಷರತೆಯ ಪ್ರಾಮುಖ್ಯತೆ ?",
    content_e: "Electoral literacy refers to having knowledge about the electoral process, such as information about candidates, voting rights of citizens, polling stations, and voting machines. Electoral literacy not only provides voters with the correct information but also empowers them with the knowledge of their voting rights. This increases people's confidence in the election process and encourages them to participate in society through their participation in elections.",
    content_h: "चुनावी साक्षरता का मतलब है चुनावी प्रक्रिया के बारे में जानकारी होना जैसे कि उम्मीदवारों की जानकारी, मतदाताओं के हक्कों की जानकारी, मतदान केंद्रों की जानकारी और वोटिंग मशीन के बारे में जानकारी। चुनावी साक्षरता न केवल मतदाताओं को सही जानकारी देती है बल्कि उन्हें उनके मताधिकारों का भी सही ज्ञान देती है। इससे लोगों में चुनाव विश्वास बढ़ता है और वे उनकी भागीदारी से समाज में भाग लेते हैं।",
    content_k: "ಚುನಾವಣಾ ಸಾಕ್ಷರತೆಯು ಚುನಾವಣೆಗಳ ಪ್ರಕ್ರಿಯೆಯ ಬಗ್ಗೆ ತಿಳಿವಳಿಕೆಯನ್ನು ಹೊಂದಿರುವುದು ಮತ್ತು ನಾಗರಿಕರು ಚುನಾವಣೆಯ ಹಕ್ಕುಗಳ ಬಗ್ಗೆ ತಿಳಿವಳಿಕೆಯನ್ನು ಹೊಂದಿರುವುದು. ಇದು ಮುಖ್ಯವಾಗಿ ನಿಜವಾದ ಮಾಹಿತಿಯನ್ನು ನೀಡುವುದು, ಮತ್ತು ನಾಗರಿಕರು ತಮ್ಮ ಮತದಾನ ಹಕ್ಕುಗಳ ಜ್ಞಾನವನ್ನು ಬೆಳಸುತ್ತದೆ. ಇದು ಜನರ ನಂಬಿಕೆಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ ಮತ್ತು ಅವರನ್ನು ಸಮಾಜದಲ್ಲಿ ಪಾಲುದಾರಿಗಳಾಗಿ ಭಾಗ ವಹಿಸುವಂತೆ ಪ್ರೋತ್ಸಾಹಿಸುತ್ತದೆ.",
  },
  {
    id: 2,
    question_e:"Why are elections is important in India ?",
    question_h:"भारत में चुनाव क्यों महत्वपूर्ण हैं ?",
    question_k:"ಭಾರತದಲ್ಲಿ ಚುನಾವಣೆ ಏಕೆ ಮುಖ್ಯ ?",
    content_e: "Elections are crucial in India as they uphold the principles of democracy, allowing citizens to exercise their right to vote and choose their leaders. They ensure fair representation, accountability, and transparency in governance. Elections also foster political participation, encourage diversity, and promote peaceful power transitions. They empower citizens to voice their opinions, safeguard their liberties, and shape the nation's direction. Overall, elections play a vital role in India's democratic fabric, promoting citizen engagement, and protecting the fundamental values of a democratic society",
    content_h: "भारत में चुनाव महत्वपूर्ण हैं क्योंकि वे लोकतंत्र के सिद्धांतों को सामर्थ्य प्रदान करते हैं, नागरिकों को मताधिकार का उपयोग करने और अपने नेता चुनने की अनुमति देते हैं। वे न्यायपूर्ण प्रतिनिधित्व, जवाबदेही और पारदर्शिता को सुनिश्चित करते हैं। चुनाव भी राजनीतिक भागीदारी को बढ़ावा देते हैं, विविधता को प्रोत्साहित करते हैं, और शांतिपूर्ण शक्ति के परिवर्तन को प्रमोट करते हैं। वे नागरिकों को अपनी राय व्यक्त करने, उनकी स्वतंत्रता की सुरक्षा करने, और राष्ट्र के दिशा-निर्देश को आकार देने में सक्षम बनाते हैं। समग्र रूप से, चुनाव भारत के लोकतांत्रिक वस्त्र के अनावरण में महत्वपूर्ण भूमिका निभाते हैं, नागरिक संवेदनशीलता को बढ़ावा देते हैं, और लोकतांत्रिक समाज के मौल्यों की सुरक्षा करते हैं।",
    content_k: "ಭಾರತದಲ್ಲಿ ಆಯ್ಕೆಗಳು ಎಷ್ಟು ಮುಖ್ಯವಾಗಿವೆ ಎಂಬುದನ್ನು ಹೇಳಲು ಅನರ್ಹವಾಗಿದೆ. ಅದು ಜನಾಧಿನ ಸಿದ್ಧಾಂತಗಳನ್ನು ಪಾಲಿಸುತ್ತದೆ, ನಾಗರಿಕರಿಗೆ ಮತ ಹೇಳಲು ಹಕ್ಕನ್ನು ನೀಡುತ್ತದೆ ಮತ್ತು ಅವರ ನಾಯಕರನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಅವರಿಗೆ ಅವಕಾಶ ನೀಡುತ್ತದೆ. ಅದು ನ್ಯಾಯತ್ವವನ್ನು ಹೊಂದಿಸುತ್ತದೆ, ಜವಾಬ್ದಾರಿಯನ್ನು ಹೊಂದಿಸುತ್ತದೆ ಮತ್ತು ಶಾಸನದಲ್ಲಿ ಪಾರದರ್ಶಕತೆಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ. ಆಯ್ಕೆಗಳು ರಾಜಕೀಯ ಭಾಗೀದಾರತ್ವವನ್ನು ಸಾಮಾಜಿಕ ಭಿನ್ನತೆಯನ್ನು ಪ್ರಚೋದಿಸುತ್ತವೆ, ಶಾಂತಿಯ ಶಕ್ತಿ ವ್ಯವಸ್ಥೆಗಳನ್ನು ಹೊಂದಿಸುತ್ತವೆ",
  },
  {
    id: 3,
    question_e:"Why youth voters in india are important ?",
    question_h:"भारत में युवा मतदाता क्यों महत्वपूर्ण हैं ? ",
    question_k:"ಭಾರತದಲ್ಲಿ ಯುವ ಮತದಾರರು ಏಕೆ ಮುಖ್ಯ ?",
    content_e: "Youth voters in India hold significant importance as they represent a considerable portion of the population. Their participation in elections can bring fresh perspectives, ideas, and demands to the political landscape. Youth voters have the power to influence policy decisions, shape the future of the country, and hold elected representatives accountable. Their active engagement in the democratic process can bring about positive changes and contribute to the overall development and progress of India.",
    content_h: "भारत में युवा मतदाता महत्वपूर्ण हैं क्योंकि वे जनसंख्या का एक महत्वपूर्ण हिस्सा प्रतिनिधित्व करते हैं। युवा मतदाताओं की भागीदारी नई दृष्टिकोण, विचार और मांगों को राजनीतिक स्थलीनता में लाती है। युवा मतदाताओं के प्रभाव से नीति निर्णयों को प्रभावित किया जा सकता है, देश के भविष्य को आकार दिया जा सकता है और निर्वाचित प्रतिनिधियों को जवाबदेह बना सकता है। युवा मतदाताओं की सक्रिय भागीदारी लौकिक बदलाव ला सकती है और भारत के समग्र विकास और प्रगति में योगदान कर सकती है।",
    content_k: "ಭಾರತದಲ್ಲಿ ಯುವ ಮತದಾರರು ಮುಖ್ಯವಾಗಿದ್ದು, ಅವರು ಜನಸಂಖ್ಯೆಯ ಒಂದು ದೊಡ್ಡ ಪಕ್ಷವನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತಾರೆ. ಚುನಾವಣೆಗಳಲ್ಲಿ ಅವರ ಭಾಗವಹಿತಿ ಹೊಂದಿದರೆ, ಹೊಸ ದೃಷ್ಟಿಕೋನಗಳು, ವಿಚಾರಗಳು ಮತ್ತು ಆಕರ್ಷಣೆಗಳನ್ನು ರಾಜಕೀಯ ಪರಿಣಾಮಕಾರಿಗೆ ತರಬಹುದು. ಯುವ ಮತದಾರರು ನೀತಿ ನಿರ್ಧಾರಗಳಿಗೆ ಪ್ರಭಾವ ಬೀರಲು, ದೇಶದ ಭವಿಷ್ಯವನ್ನು ರೂಪಿಸಲು ಮತ್ತು ಆಯ್ಕೆಗೆ ಹೊಣೆಯಾಗಿರುತ್ತಾರೆ. ಯುವ ಮತದಾರರ ಸಕ್ರಿಯ ಭಾಗಿಗತದಿಂದ ಸಾಮಾಜಿಕ ಬೆಳವಣಿಗೆಗೆ ಸಹಾಯ ಮಾಡಿ ದೇಶದ ಸಾಮ್ರಾಜ್ಯ ಹಾಗೂ ಪ್ರಗತಿಗೆ ಕೊಡುಗೆ ನೀಡಬಹುದು.",
  },
  {
    id: 4,
    question_e:"How election will benefit for all in india ?",
    question_h:"भारत में सभी के लिए कैसे फायदेमंद होगा चुनाव ?",
    question_k:"ಭಾರತದಲ್ಲಿ ಎಲ್ಲರಿಗೂ ಚುನಾವಣೆ ಹೇಗೆ ಲಾಭವಾಗುತ್ತದೆ ?",
    content_e: "Elections in India benefit all citizens in multiple ways. They provide an opportunity for people to choose their leaders and voice their opinions. Through the electoral process, citizens can hold elected representatives accountable, influence policy decisions, and shape the direction of the country. Elections also promote democratic values, civic engagement, and political awareness. They foster a sense of participation and inclusivity, and ensure that power is vested in the hands of the people. Overall, elections in India contribute to the strengthening of democracy and the well-being of all citizens",
    content_h: "का मौका प्रदान करते हैं। चुनावी प्रक्रिया के माध्यम से नागरिक चुने गए प्रतिनिधियों को जवाबदेह बना सकते हैं, नीति निर्धारण पर प्रभाव डाल सकते हैं, और देश के दिशा-निर्देश को आकार दे सकते हैं। चुनाव लोकतांत्रिक मूल्यों, नागरिक संलग्नता और राजनैतिक जागरूकता को बढ़ावा देते हैं। इन्हें भागीदारी और समावेशी भावना को प्रोत्साहित करते हैं और सत्ता को जनता के हाथ में स्थापित करते हैं। समग्र रूप से, भारत में चुनाव लोकतंत्र को मजबूत करते हैं और सभी नागरिकों के कल्याण को सुनिश्चित करते हैं।",
    content_k: "ಭಾರತದಲ್ಲಿ ಚುನಾವಣೆ ಹೇಗೆ ಎಲ್ಲರಿಗೂ ಪ್ರಯೋಜನವನ್ನು ತರುತ್ತದೆಂದು ಹೇಳಬೇಕಾದರೆ ಇದು ಹೀಗಿದೆ - ಚುನಾವಣೆ ಮೂಲಕ ಪ್ರಜಾಪ್ರಭುತ್ವದಲ್ಲಿ ಸಮಾನ ಮೌಲ್ಯ ಹೊಂದಿರುವ ಅಧಿಕಾರವನ್ನು ಹೊಂದುವ ಅವಕಾಶವನ್ನು ನೀಡುತ್ತದೆ. ಜನರಲಿ ಹೊಂದಿರುವ ಮತ ಮತ್ತು ಹಕ್ಕುಗಳನ್ನು ಮೆಚ್ಚಿಸುವುದರಿಂದ ಅವರಿಗೆ ಸ್ವಾಧೀನತೆ ಮತ್ತು ಪ್ರಭಾವ ದೊರಕುತ್ತದೆ. ಮತದಾರರ ಮೌಲ್ಯಗಳನ್ನು ಪ್ರಾಮುಖ್ಯತೆ ನೀಡುತ್ತದೆ, ಹಾಗೂ ಜನರು ತಮ್ಮ ನ್ಯಾಯಾಂಗ ಮುಖ್ಯಮಂತ್ರಿಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡುವ ಹಕ್ಕುಗಳನ್ನು ಹೊಂದುತ್ತಾರೆ",
  },
  {
    id: 5,
    question_e:"How India is inspiration for other countries to vote ?",
    question_h:"भारत अन्य देशों के लिए मतदान करने के लिए कैसे प्रेरणा है ?",
    question_k:"ಮತ ಚಲಾಯಿಸಲು ಇತರ ದೇಶಗಳಿಗೆ ಭಾರತ ಹೇಗೆ ಸ್ಫೂರ್ತಿಯಾಗಿದೆ ?",
    content_e: "India, being the largest democracy in the world, has been an inspiration for many other countries to adopt the democratic process and encourage citizens to exercise their right to vote. India's successful conduct of free and fair elections, where over 900 million eligible voters participated in the 2019 general elections, has set an example for the world. The Election Commission of India has also taken several initiatives to ensure maximum participation of citizens in the electoral process, such as voter education programs, easy registration, and voter-friendly facilities at polling stations.",
    content_h: "भारत दुनिया की सबसे बड़ी लोकतंत्र होने के नाते, अन्य देशों के लिए लोकतंत्र की प्रक्रिया को अपनाने और नागरिकों को वोट देने के लिए प्रोत्साहित करने के लिए प्रेरणा देता है। भारत ने 2019 के सामान्य चुनाव में 9 अरब से अधिक योग्य मतदाताओं ने भाग लिया था, जो दुनिया के लिए एक उदाहरण साबित होता है। भारत की चुनाव आयोग ने भी मतदाताओं की अधिकतम भागीदारी सुनिश्चित करने के लिए कई पहल की हैं, जैसे मतदाता शिक्षा कार्यक्रम, आसान रजिस्ट्रेशन और मतदान स्थानों पर मतदाता मित्रता। अन्य देश भारत के अनुभव से सीख सकते हैं और अपनी चुनावी प्रक्रिया को अधिक सुलभ और समावेशी बनाने के लिए प्रयास कर सकते हैं।",
    content_k: "ಭಾರತ ಲೋಕತಂತ್ರದ ಜೊತೆಗೆ ಜಗತ್ತಿನಲ್ಲೇ ಅತ್ಯಂತ ಪ್ರಭಾವಶಾಲೀ ದೇಶಗಳಲ್ಲೊಂದು. ಅದರ ಪ್ರಭಾವ ಜಗತ್ತಿನ ಹಲವಾರು ದೇಶಗಳಿಗೆ ಹೊಸ ಮಾರ್ಗದರ್ಶನ ಹಾಗೂ ಮೂಲಭೂತ ಅಧಿಕಾರದ ಪ್ರತಿನಿಧಿಗಳನ್ನು ಹೊಂದಿಸಿದೆ. ಭಾರತದಲ್ಲಿ ನಡೆದ ನಿಷ್ಪಕ್ಷ ಮತದಾನದ ವ್ಯವಸ್ಥೆಯು ವಿಶ್ವದ ಉದಾಹರಣೆಯಾಗಿದೆ. 2019 ಸಾಮಾನ್ಯ ಆರ್ಧಿಕ ಚುನಾವಣೆಯಲ್ಲಿ 90 ಕೋಟಿಯಷ್ಟು ಯೋಗ್ಯತೆಯುಳ್ಳ ಮತದಾರರು ಪಾಲ್ಗೊಂಡಿದ್ದರು. ಭಾರತದ ಮತದಾನ ಆಯೋಗ ಮತದಾತರರ ಪ್ರತಿಭಟನೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಅನೇಕ ಪದಕ್ಷೇಪಗಳನ್ನು ಹೊಂದಿದೆ, ಅವುಗಳಲ್ಲಿ ಮತದಾತರ ಶಿಕ್ಷಣ ಕಾರ್ಯಕ್ರಮ, ಸುಲಭ ನೋಂದಣಿ",
  },
];
